# Generated by Django 5.1.1 on 2024-09-27 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuthModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=225, unique=True)),
                ('name', models.CharField(max_length=225)),
                ('password', models.CharField(max_length=225)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
